on:
  push:
    branches:
    - master

env:
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20230810121555.azurecr.io
  CONTAINER_APP_NAME: containerapp20230810121017
  CONTAINER_APP_RESOURCE_GROUP_NAME: webfrontend-container-app-1234
  CONTAINER_APP_CONTAINER_NAME: containerapp
  DOCKER_FILEPATH_WEBAPI: docker/ComposeSample/WebApi/Dockerfile
  DOCKER_FILEPATH_WEBFRONTEND: docker/ComposeSample/WebFrontend/Dockerfile
jobs:
  WebApi_buildImageAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.registry20230810121555_USERNAME_6891 }}
        password: ${{ secrets.registry20230810121555_PASSWORD_6891 }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/webapi:${{ github.sha }}
        file: ${{ env.DOCKER_FILEPATH_WEBAPI }}
    - name: Azure login
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.WEBAPI_USERNAME }} -p ${{ secrets.WEBAPI_PASSWORD }} --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
          az account list
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.REGISTRY20230810121555_USERNAME_6891 }} --password $${{ secrets.REGISTRY20230810121555_PASSWORD_6891 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/webapi:${{ github.sha }}
    - name: Azure logout
      run: az logout
  WebFrontEnd_buildImageAndDeploy:
    runs-on: ubuntu-latest
    needs: WebApi_buildImageAndDeploy
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.registry20230810121555_USERNAME_2047 }}
        password: ${{ secrets.registry20230810121555_PASSWORD_2047 }}
    - name: Build and push Docker image to Azure container registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/webfrontend:${{ github.sha }}
        file: ${{ env.DOCKER_FILEPATH_WEBFRONTEND }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.containerapp20230810121017_SPN }}
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.registry20230810121555_USERNAME_2047 }} --password ${{ secrets.registry20230810121555_PASSWORD_2047 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/webfrontend:${{ github.sha }}
    - name: Azure logout
      run: az logout
